//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8825.
// 
namespace WMSMobileClient.WMSSyncService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WMSSyncServiceSoap", Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class WMSSyncService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WMSSyncService() {
            this.Url = "http://10.1.10.29/WMSSyncServ/WMSSyncService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_TestLogFile", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SOA_TestLogFile() {
            this.Invoke("SOA_TestLogFile", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_TestLogFile(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_TestLogFile", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSOA_TestLogFile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_WebServiceVersion", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SOA_WebServiceVersion() {
            object[] results = this.Invoke("SOA_WebServiceVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_WebServiceVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_WebServiceVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSOA_WebServiceVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/OrderDetailsList", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TOrderDetails[] OrderDetailsList(long dsrnumber, short compid, short branchid) {
            object[] results = this.Invoke("OrderDetailsList", new object[] {
                        dsrnumber,
                        compid,
                        branchid});
            return ((TOrderDetails[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOrderDetailsList(long dsrnumber, short compid, short branchid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OrderDetailsList", new object[] {
                        dsrnumber,
                        compid,
                        branchid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TOrderDetails[] EndOrderDetailsList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TOrderDetails[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/ConnectionStatus", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConnectionStatus() {
            object[] results = this.Invoke("ConnectionStatus", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConnectionStatus(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConnectionStatus", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndConnectionStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/GetTransCodeHeader", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransCodeHeader GetTransCodeHeader(long ftrid) {
            object[] results = this.Invoke("GetTransCodeHeader", new object[] {
                        ftrid});
            return ((TransCodeHeader)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTransCodeHeader(long ftrid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTransCodeHeader", new object[] {
                        ftrid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TransCodeHeader EndGetTransCodeHeader(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransCodeHeader)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/GetTransCodeDetails", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransCodeDetail[] GetTransCodeDetails(long ftrid) {
            object[] results = this.Invoke("GetTransCodeDetails", new object[] {
                        ftrid});
            return ((TransCodeDetail[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTransCodeDetails(long ftrid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTransCodeDetails", new object[] {
                        ftrid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TransCodeDetail[] EndGetTransCodeDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransCodeDetail[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/Test", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransCodeDetail Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((TransCodeDetail)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTest(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Test", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TransCodeDetail EndTest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransCodeDetail)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/AwakeDB", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AwakeDB() {
            this.Invoke("AwakeDB", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAwakeDB(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AwakeDB", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAwakeDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/getclasses", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long getclasses(SyncERPItem serpitem) {
            object[] results = this.Invoke("getclasses", new object[] {
                        serpitem});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetclasses(SyncERPItem serpitem, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getclasses", new object[] {
                        serpitem}, callback, asyncState);
        }
        
        /// <remarks/>
        public long Endgetclasses(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_CreateItemData", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncInfo SOA_CreateItemData(int StoreID, bool getzeroqtys, string lastsyncdate) {
            object[] results = this.Invoke("SOA_CreateItemData", new object[] {
                        StoreID,
                        getzeroqtys,
                        lastsyncdate});
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_CreateItemData(int StoreID, bool getzeroqtys, string lastsyncdate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_CreateItemData", new object[] {
                        StoreID,
                        getzeroqtys,
                        lastsyncdate}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncInfo EndSOA_CreateItemData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_CreateLotData", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncInfo SOA_CreateLotData(int StoreID, bool getzeroqtys, string lastsyncdate) {
            object[] results = this.Invoke("SOA_CreateLotData", new object[] {
                        StoreID,
                        getzeroqtys,
                        lastsyncdate});
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_CreateLotData(int StoreID, bool getzeroqtys, string lastsyncdate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_CreateLotData", new object[] {
                        StoreID,
                        getzeroqtys,
                        lastsyncdate}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncInfo EndSOA_CreateLotData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetNewItems", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncERPItem[] SOA_GetNewItems(int StoreID, string lastsyncdate) {
            object[] results = this.Invoke("SOA_GetNewItems", new object[] {
                        StoreID,
                        lastsyncdate});
            return ((SyncERPItem[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetNewItems(int StoreID, string lastsyncdate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetNewItems", new object[] {
                        StoreID,
                        lastsyncdate}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncERPItem[] EndSOA_GetNewItems(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncERPItem[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetNewLots", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncLot[] SOA_GetNewLots(int StoreID, string lastsyncdate) {
            object[] results = this.Invoke("SOA_GetNewLots", new object[] {
                        StoreID,
                        lastsyncdate});
            return ((SyncLot[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetNewLots(int StoreID, string lastsyncdate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetNewLots", new object[] {
                        StoreID,
                        lastsyncdate}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncLot[] EndSOA_GetNewLots(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncLot[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/TestERPcon", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long TestERPcon() {
            object[] results = this.Invoke("TestERPcon", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTestERPcon(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestERPcon", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndTestERPcon(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_ClearTemporaryData", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SOA_ClearTemporaryData(int StoreID) {
            object[] results = this.Invoke("SOA_ClearTemporaryData", new object[] {
                        StoreID});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_ClearTemporaryData(int StoreID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_ClearTemporaryData", new object[] {
                        StoreID}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndSOA_ClearTemporaryData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/ImportPackingListCType", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportPackingListCType(PackingListDetail[] pack) {
            object[] results = this.Invoke("ImportPackingListCType", new object[] {
                        pack});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportPackingListCType(PackingListDetail[] pack, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportPackingListCType", new object[] {
                        pack}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportPackingListCType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/CreateTradeCodeOnTheFly", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateTradeCodeOnTheFly(PackingListHeader packheader, PackingListDetail[] pack, int compid, int branchid, int storeid, int dsrid, int fpa) {
            object[] results = this.Invoke("CreateTradeCodeOnTheFly", new object[] {
                        packheader,
                        pack,
                        compid,
                        branchid,
                        storeid,
                        dsrid,
                        fpa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateTradeCodeOnTheFly(PackingListHeader packheader, PackingListDetail[] pack, int compid, int branchid, int storeid, int dsrid, int fpa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateTradeCodeOnTheFly", new object[] {
                        packheader,
                        pack,
                        compid,
                        branchid,
                        storeid,
                        dsrid,
                        fpa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCreateTradeCodeOnTheFly(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/ImportPackingListHeaderCType", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportPackingListHeaderCType(PackingListHeader packhdr) {
            object[] results = this.Invoke("ImportPackingListHeaderCType", new object[] {
                        packhdr});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportPackingListHeaderCType(PackingListHeader packhdr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportPackingListHeaderCType", new object[] {
                        packhdr}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportPackingListHeaderCType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_CreateTemporaryData", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncInfo SOA_CreateTemporaryData(int StoreID) {
            object[] results = this.Invoke("SOA_CreateTemporaryData", new object[] {
                        StoreID});
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_CreateTemporaryData(int StoreID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_CreateTemporaryData", new object[] {
                        StoreID}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncInfo EndSOA_CreateTemporaryData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/GetERPOrderID", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetERPOrderID(string dsrnumber) {
            object[] results = this.Invoke("GetERPOrderID", new object[] {
                        dsrnumber});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetERPOrderID(string dsrnumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetERPOrderID", new object[] {
                        dsrnumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndGetERPOrderID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetMUnits", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERPMunit[] SOA_GetMUnits() {
            object[] results = this.Invoke("SOA_GetMUnits", new object[0]);
            return ((ERPMunit[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetMUnits(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetMUnits", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public ERPMunit[] EndSOA_GetMUnits(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ERPMunit[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetStores", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERPStore[] SOA_GetStores(short CompID) {
            object[] results = this.Invoke("SOA_GetStores", new object[] {
                        CompID});
            return ((ERPStore[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetStores(short CompID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetStores", new object[] {
                        CompID}, callback, asyncState);
        }
        
        /// <remarks/>
        public ERPStore[] EndSOA_GetStores(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ERPStore[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetNewItem", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncERPItem SOA_GetNewItem(long itemid) {
            object[] results = this.Invoke("SOA_GetNewItem", new object[] {
                        itemid});
            return ((SyncERPItem)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetNewItem(long itemid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetNewItem", new object[] {
                        itemid}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncERPItem EndSOA_GetNewItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncERPItem)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetNewLot", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncLot SOA_GetNewLot(long lotid) {
            object[] results = this.Invoke("SOA_GetNewLot", new object[] {
                        lotid});
            return ((SyncLot)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetNewLot(long lotid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetNewLot", new object[] {
                        lotid}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncLot EndSOA_GetNewLot(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncLot)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetNewLotbyCode", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncLot SOA_GetNewLotbyCode(string lotcode) {
            object[] results = this.Invoke("SOA_GetNewLotbyCode", new object[] {
                        lotcode});
            return ((SyncLot)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetNewLotbyCode(string lotcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetNewLotbyCode", new object[] {
                        lotcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncLot EndSOA_GetNewLotbyCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncLot)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetInventoryLots", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncLot[] SOA_GetInventoryLots(int StoreID, long StartID, long EndID) {
            object[] results = this.Invoke("SOA_GetInventoryLots", new object[] {
                        StoreID,
                        StartID,
                        EndID});
            return ((SyncLot[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetInventoryLots(int StoreID, long StartID, long EndID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetInventoryLots", new object[] {
                        StoreID,
                        StartID,
                        EndID}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncLot[] EndSOA_GetInventoryLots(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncLot[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetInventoryItems", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncERPItem[] SOA_GetInventoryItems(int StoreID, long StartID, long EndID) {
            object[] results = this.Invoke("SOA_GetInventoryItems", new object[] {
                        StoreID,
                        StartID,
                        EndID});
            return ((SyncERPItem[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetInventoryItems(int StoreID, long StartID, long EndID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetInventoryItems", new object[] {
                        StoreID,
                        StartID,
                        EndID}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncERPItem[] EndSOA_GetInventoryItems(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncERPItem[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetItemsList", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncERPItem[] SOA_GetItemsList(int storeid, int branchid, long startindex, long endindex) {
            object[] results = this.Invoke("SOA_GetItemsList", new object[] {
                        storeid,
                        branchid,
                        startindex,
                        endindex});
            return ((SyncERPItem[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetItemsList(int storeid, int branchid, long startindex, long endindex, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetItemsList", new object[] {
                        storeid,
                        branchid,
                        startindex,
                        endindex}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncERPItem[] EndSOA_GetItemsList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncERPItem[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/SOA_GetLotsList", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncLot[] SOA_GetLotsList(int storeid, int branchid, long startindex, long endindex) {
            object[] results = this.Invoke("SOA_GetLotsList", new object[] {
                        storeid,
                        branchid,
                        startindex,
                        endindex});
            return ((SyncLot[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetLotsList(int storeid, int branchid, long startindex, long endindex, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetLotsList", new object[] {
                        storeid,
                        branchid,
                        startindex,
                        endindex}, callback, asyncState);
        }
        
        /// <remarks/>
        public SyncLot[] EndSOA_GetLotsList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncLot[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/ClearGItemList", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ClearGItemList(int branchid) {
            object[] results = this.Invoke("ClearGItemList", new object[] {
                        branchid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearGItemList(int branchid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClearGItemList", new object[] {
                        branchid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndClearGItemList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/ClearGLotList", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ClearGLotList(int branchid) {
            object[] results = this.Invoke("ClearGLotList", new object[] {
                        branchid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearGLotList(int branchid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClearGLotList", new object[] {
                        branchid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndClearGLotList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/CarpetCleaningTrans", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CarpetCleaningTrans(CarpetTrans[] storetranslist) {
            object[] results = this.Invoke("CarpetCleaningTrans", new object[] {
                        storetranslist});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCarpetCleaningTrans(CarpetTrans[] storetranslist, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CarpetCleaningTrans", new object[] {
                        storetranslist}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndCarpetCleaningTrans(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/GetCustomerbycode", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer GetCustomerbycode(string customercode) {
            object[] results = this.Invoke("GetCustomerbycode", new object[] {
                        customercode});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomerbycode(string customercode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomerbycode", new object[] {
                        customercode}, callback, asyncState);
        }
        
        /// <remarks/>
        public Customer EndGetCustomerbycode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WMSSyncService.intranet.albio.gr/CarpetCleaningCancelTrans", RequestNamespace="http://WMSSyncService.intranet.albio.gr/", ResponseNamespace="http://WMSSyncService.intranet.albio.gr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CarpetCleaningCancelTrans(long wmstransid) {
            object[] results = this.Invoke("CarpetCleaningCancelTrans", new object[] {
                        wmstransid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCarpetCleaningCancelTrans(long wmstransid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CarpetCleaningCancelTrans", new object[] {
                        wmstransid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndCarpetCleaningCancelTrans(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class TOrderDetails {
        
        private int idField;
        
        private long orderdtlidField;
        
        private short compidField;
        
        private long orderidField;
        
        private long itemidField;
        
        private long itemlotidField;
        
        private decimal itemqtyprimaryField;
        
        private short munitprimaryField;
        
        private long itemqtysecondaryField;
        
        private short munitsecondaryField;
        
        private string dateentryField;
        
        private string orderdateField;
        
        private string requesteddelivdateField;
        
        private string promiseddelivdateField;
        
        private short orderdtlstatusField;
        
        private decimal priceperunitField;
        
        private short moneytypeField;
        
        private decimal itemqtypriceField;
        
        private decimal itemlengthField;
        
        private int itemcoloridField;
        
        private bool paintedField;
        
        private int itemcolorid2Field;
        
        private string orderdtlcommentsField;
        
        private int packtypeField;
        
        private int hardnessField;
        
        private long accerpitemidField;
        
        private long erporderdtlidField;
        
        private decimal prdiscountField;
        
        private decimal specialpriceField;
        
        private long weborderdtlidField;
        
        private long weborderidField;
        
        private string weekshippingField;
        
        private string dbreccreatehostField;
        
        private string dbreccreatedateField;
        
        private int dbreccreateuserField;
        
        private string dbrecmoddateField;
        
        private int dbrecmoduserField;
        
        private string dbrecmodhostField;
        
        private short servbranchidField;
        
        private string itemcodeField;
        
        private string itemdescField;
        
        private string colordescField;
        
        private short munitdecimalsField;
        
        private string ordercodeField;
        
        private long customeridField;
        
        private string customertitleField;
        
        private decimal itemrequestedqtyField;
        
        private decimal itempqtyfreeField;
        
        private decimal itemdoneqtyField;
        
        private decimal shippedpqtyField;
        
        private decimal itemqtybalanceField;
        
        private decimal itemqtyshippbalanceField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long orderdtlid {
            get {
                return this.orderdtlidField;
            }
            set {
                this.orderdtlidField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public long orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        public long itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        public long itemlotid {
            get {
                return this.itemlotidField;
            }
            set {
                this.itemlotidField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtyprimary {
            get {
                return this.itemqtyprimaryField;
            }
            set {
                this.itemqtyprimaryField = value;
            }
        }
        
        /// <remarks/>
        public short munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public long itemqtysecondary {
            get {
                return this.itemqtysecondaryField;
            }
            set {
                this.itemqtysecondaryField = value;
            }
        }
        
        /// <remarks/>
        public short munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public string dateentry {
            get {
                return this.dateentryField;
            }
            set {
                this.dateentryField = value;
            }
        }
        
        /// <remarks/>
        public string orderdate {
            get {
                return this.orderdateField;
            }
            set {
                this.orderdateField = value;
            }
        }
        
        /// <remarks/>
        public string requesteddelivdate {
            get {
                return this.requesteddelivdateField;
            }
            set {
                this.requesteddelivdateField = value;
            }
        }
        
        /// <remarks/>
        public string promiseddelivdate {
            get {
                return this.promiseddelivdateField;
            }
            set {
                this.promiseddelivdateField = value;
            }
        }
        
        /// <remarks/>
        public short orderdtlstatus {
            get {
                return this.orderdtlstatusField;
            }
            set {
                this.orderdtlstatusField = value;
            }
        }
        
        /// <remarks/>
        public decimal priceperunit {
            get {
                return this.priceperunitField;
            }
            set {
                this.priceperunitField = value;
            }
        }
        
        /// <remarks/>
        public short moneytype {
            get {
                return this.moneytypeField;
            }
            set {
                this.moneytypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtyprice {
            get {
                return this.itemqtypriceField;
            }
            set {
                this.itemqtypriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemlength {
            get {
                return this.itemlengthField;
            }
            set {
                this.itemlengthField = value;
            }
        }
        
        /// <remarks/>
        public int itemcolorid {
            get {
                return this.itemcoloridField;
            }
            set {
                this.itemcoloridField = value;
            }
        }
        
        /// <remarks/>
        public bool painted {
            get {
                return this.paintedField;
            }
            set {
                this.paintedField = value;
            }
        }
        
        /// <remarks/>
        public int itemcolorid2 {
            get {
                return this.itemcolorid2Field;
            }
            set {
                this.itemcolorid2Field = value;
            }
        }
        
        /// <remarks/>
        public string orderdtlcomments {
            get {
                return this.orderdtlcommentsField;
            }
            set {
                this.orderdtlcommentsField = value;
            }
        }
        
        /// <remarks/>
        public int packtype {
            get {
                return this.packtypeField;
            }
            set {
                this.packtypeField = value;
            }
        }
        
        /// <remarks/>
        public int hardness {
            get {
                return this.hardnessField;
            }
            set {
                this.hardnessField = value;
            }
        }
        
        /// <remarks/>
        public long accerpitemid {
            get {
                return this.accerpitemidField;
            }
            set {
                this.accerpitemidField = value;
            }
        }
        
        /// <remarks/>
        public long erporderdtlid {
            get {
                return this.erporderdtlidField;
            }
            set {
                this.erporderdtlidField = value;
            }
        }
        
        /// <remarks/>
        public decimal prdiscount {
            get {
                return this.prdiscountField;
            }
            set {
                this.prdiscountField = value;
            }
        }
        
        /// <remarks/>
        public decimal specialprice {
            get {
                return this.specialpriceField;
            }
            set {
                this.specialpriceField = value;
            }
        }
        
        /// <remarks/>
        public long weborderdtlid {
            get {
                return this.weborderdtlidField;
            }
            set {
                this.weborderdtlidField = value;
            }
        }
        
        /// <remarks/>
        public long weborderid {
            get {
                return this.weborderidField;
            }
            set {
                this.weborderidField = value;
            }
        }
        
        /// <remarks/>
        public string weekshipping {
            get {
                return this.weekshippingField;
            }
            set {
                this.weekshippingField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatehost {
            get {
                return this.dbreccreatehostField;
            }
            set {
                this.dbreccreatehostField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatedate {
            get {
                return this.dbreccreatedateField;
            }
            set {
                this.dbreccreatedateField = value;
            }
        }
        
        /// <remarks/>
        public int dbreccreateuser {
            get {
                return this.dbreccreateuserField;
            }
            set {
                this.dbreccreateuserField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmoddate {
            get {
                return this.dbrecmoddateField;
            }
            set {
                this.dbrecmoddateField = value;
            }
        }
        
        /// <remarks/>
        public int dbrecmoduser {
            get {
                return this.dbrecmoduserField;
            }
            set {
                this.dbrecmoduserField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmodhost {
            get {
                return this.dbrecmodhostField;
            }
            set {
                this.dbrecmodhostField = value;
            }
        }
        
        /// <remarks/>
        public short servbranchid {
            get {
                return this.servbranchidField;
            }
            set {
                this.servbranchidField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
        
        /// <remarks/>
        public string colordesc {
            get {
                return this.colordescField;
            }
            set {
                this.colordescField = value;
            }
        }
        
        /// <remarks/>
        public short munitdecimals {
            get {
                return this.munitdecimalsField;
            }
            set {
                this.munitdecimalsField = value;
            }
        }
        
        /// <remarks/>
        public string ordercode {
            get {
                return this.ordercodeField;
            }
            set {
                this.ordercodeField = value;
            }
        }
        
        /// <remarks/>
        public long customerid {
            get {
                return this.customeridField;
            }
            set {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        public string customertitle {
            get {
                return this.customertitleField;
            }
            set {
                this.customertitleField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemrequestedqty {
            get {
                return this.itemrequestedqtyField;
            }
            set {
                this.itemrequestedqtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal itempqtyfree {
            get {
                return this.itempqtyfreeField;
            }
            set {
                this.itempqtyfreeField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemdoneqty {
            get {
                return this.itemdoneqtyField;
            }
            set {
                this.itemdoneqtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal shippedpqty {
            get {
                return this.shippedpqtyField;
            }
            set {
                this.shippedpqtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtybalance {
            get {
                return this.itemqtybalanceField;
            }
            set {
                this.itemqtybalanceField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtyshippbalance {
            get {
                return this.itemqtyshippbalanceField;
            }
            set {
                this.itemqtyshippbalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class Customer {
        
        private long erpCustomerIDField;
        
        private string customerCodeField;
        
        private string customerTitleField;
        
        private string occupationField;
        
        private string sTREET1Field;
        
        private string zIPCODE1Field;
        
        private string cITY1Field;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string fAX1Field;
        
        private string zALPISCODEField;
        
        /// <remarks/>
        public long erpCustomerID {
            get {
                return this.erpCustomerIDField;
            }
            set {
                this.erpCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTitle {
            get {
                return this.customerTitleField;
            }
            set {
                this.customerTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        public string STREET1 {
            get {
                return this.sTREET1Field;
            }
            set {
                this.sTREET1Field = value;
            }
        }
        
        /// <remarks/>
        public string ZIPCODE1 {
            get {
                return this.zIPCODE1Field;
            }
            set {
                this.zIPCODE1Field = value;
            }
        }
        
        /// <remarks/>
        public string CITY1 {
            get {
                return this.cITY1Field;
            }
            set {
                this.cITY1Field = value;
            }
        }
        
        /// <remarks/>
        public string phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        public string phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        public string FAX1 {
            get {
                return this.fAX1Field;
            }
            set {
                this.fAX1Field = value;
            }
        }
        
        /// <remarks/>
        public string ZALPISCODE {
            get {
                return this.zALPISCODEField;
            }
            set {
                this.zALPISCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class CarpetTrans {
        
        private long tRANSIDField;
        
        private short eRPCompIDField;
        
        private short eRPBRACHIDField;
        
        private long alpisStoreTransIDField;
        
        private long wMSTRANSIDField;
        
        private string alpisStoreTransDateField;
        
        private long eRPTransSeriesIDField;
        
        private long eRPCustomerIDField;
        
        private long eRPSupplierIDField;
        
        private long eRPFromStoreIDField;
        
        private long eRPToStoreIDField;
        
        private long eRPItemIDField;
        
        private long eRPItemMUnitField;
        
        private long eRPItemSMUnitField;
        
        private decimal eRPItemQtyField;
        
        private decimal eRPITEMSQTYField;
        
        private decimal eRPItemUnitPriceField;
        
        private decimal eRPItemQtyPriceField;
        
        private string eXTRASERVICEField;
        
        private string eRPTRANSCODEField;
        
        private long dOCTYPEField;
        
        private short isnewField;
        
        /// <remarks/>
        public long TRANSID {
            get {
                return this.tRANSIDField;
            }
            set {
                this.tRANSIDField = value;
            }
        }
        
        /// <remarks/>
        public short ERPCompID {
            get {
                return this.eRPCompIDField;
            }
            set {
                this.eRPCompIDField = value;
            }
        }
        
        /// <remarks/>
        public short ERPBRACHID {
            get {
                return this.eRPBRACHIDField;
            }
            set {
                this.eRPBRACHIDField = value;
            }
        }
        
        /// <remarks/>
        public long AlpisStoreTransID {
            get {
                return this.alpisStoreTransIDField;
            }
            set {
                this.alpisStoreTransIDField = value;
            }
        }
        
        /// <remarks/>
        public long WMSTRANSID {
            get {
                return this.wMSTRANSIDField;
            }
            set {
                this.wMSTRANSIDField = value;
            }
        }
        
        /// <remarks/>
        public string AlpisStoreTransDate {
            get {
                return this.alpisStoreTransDateField;
            }
            set {
                this.alpisStoreTransDateField = value;
            }
        }
        
        /// <remarks/>
        public long ERPTransSeriesID {
            get {
                return this.eRPTransSeriesIDField;
            }
            set {
                this.eRPTransSeriesIDField = value;
            }
        }
        
        /// <remarks/>
        public long ERPCustomerID {
            get {
                return this.eRPCustomerIDField;
            }
            set {
                this.eRPCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        public long ERPSupplierID {
            get {
                return this.eRPSupplierIDField;
            }
            set {
                this.eRPSupplierIDField = value;
            }
        }
        
        /// <remarks/>
        public long ERPFromStoreID {
            get {
                return this.eRPFromStoreIDField;
            }
            set {
                this.eRPFromStoreIDField = value;
            }
        }
        
        /// <remarks/>
        public long ERPToStoreID {
            get {
                return this.eRPToStoreIDField;
            }
            set {
                this.eRPToStoreIDField = value;
            }
        }
        
        /// <remarks/>
        public long ERPItemID {
            get {
                return this.eRPItemIDField;
            }
            set {
                this.eRPItemIDField = value;
            }
        }
        
        /// <remarks/>
        public long ERPItemMUnit {
            get {
                return this.eRPItemMUnitField;
            }
            set {
                this.eRPItemMUnitField = value;
            }
        }
        
        /// <remarks/>
        public long ERPItemSMUnit {
            get {
                return this.eRPItemSMUnitField;
            }
            set {
                this.eRPItemSMUnitField = value;
            }
        }
        
        /// <remarks/>
        public decimal ERPItemQty {
            get {
                return this.eRPItemQtyField;
            }
            set {
                this.eRPItemQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ERPITEMSQTY {
            get {
                return this.eRPITEMSQTYField;
            }
            set {
                this.eRPITEMSQTYField = value;
            }
        }
        
        /// <remarks/>
        public decimal ERPItemUnitPrice {
            get {
                return this.eRPItemUnitPriceField;
            }
            set {
                this.eRPItemUnitPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal ERPItemQtyPrice {
            get {
                return this.eRPItemQtyPriceField;
            }
            set {
                this.eRPItemQtyPriceField = value;
            }
        }
        
        /// <remarks/>
        public string EXTRASERVICE {
            get {
                return this.eXTRASERVICEField;
            }
            set {
                this.eXTRASERVICEField = value;
            }
        }
        
        /// <remarks/>
        public string ERPTRANSCODE {
            get {
                return this.eRPTRANSCODEField;
            }
            set {
                this.eRPTRANSCODEField = value;
            }
        }
        
        /// <remarks/>
        public long DOCTYPE {
            get {
                return this.dOCTYPEField;
            }
            set {
                this.dOCTYPEField = value;
            }
        }
        
        /// <remarks/>
        public short isnew {
            get {
                return this.isnewField;
            }
            set {
                this.isnewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class ERPStore {
        
        private short storeIDField;
        
        private string storeNameField;
        
        private short compIDField;
        
        /// <remarks/>
        public short storeID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string storeName {
            get {
                return this.storeNameField;
            }
            set {
                this.storeNameField = value;
            }
        }
        
        /// <remarks/>
        public short compID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class ERPMunit {
        
        private int munitIDField;
        
        private short compIDField;
        
        private string mUnitField;
        
        private short munitDecimalsField;
        
        /// <remarks/>
        public int munitID {
            get {
                return this.munitIDField;
            }
            set {
                this.munitIDField = value;
            }
        }
        
        /// <remarks/>
        public short compID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public string mUnit {
            get {
                return this.mUnitField;
            }
            set {
                this.mUnitField = value;
            }
        }
        
        /// <remarks/>
        public short munitDecimals {
            get {
                return this.munitDecimalsField;
            }
            set {
                this.munitDecimalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class PackingListHeader {
        
        private long packingListHeaderIDField;
        
        private long packinglistserveridField;
        
        private string packinglistcommentsField;
        
        private short packingListStatusField;
        
        private string customerCodeField;
        
        private string customerTitleField;
        
        private string packingListDateField;
        
        private short compidField;
        
        private short branchidField;
        
        private int storeIDField;
        
        private string storeNameField;
        
        private short kindidField;
        
        private int transTypeField;
        
        private string transCodeField;
        
        private long orderIDField;
        
        private long orderDtlIDField;
        
        private long dSRIDField;
        
        /// <remarks/>
        public long PackingListHeaderID {
            get {
                return this.packingListHeaderIDField;
            }
            set {
                this.packingListHeaderIDField = value;
            }
        }
        
        /// <remarks/>
        public long Packinglistserverid {
            get {
                return this.packinglistserveridField;
            }
            set {
                this.packinglistserveridField = value;
            }
        }
        
        /// <remarks/>
        public string Packinglistcomments {
            get {
                return this.packinglistcommentsField;
            }
            set {
                this.packinglistcommentsField = value;
            }
        }
        
        /// <remarks/>
        public short PackingListStatus {
            get {
                return this.packingListStatusField;
            }
            set {
                this.packingListStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTitle {
            get {
                return this.customerTitleField;
            }
            set {
                this.customerTitleField = value;
            }
        }
        
        /// <remarks/>
        public string PackingListDate {
            get {
                return this.packingListDateField;
            }
            set {
                this.packingListDateField = value;
            }
        }
        
        /// <remarks/>
        public short Compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short Branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public int StoreID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string StoreName {
            get {
                return this.storeNameField;
            }
            set {
                this.storeNameField = value;
            }
        }
        
        /// <remarks/>
        public short Kindid {
            get {
                return this.kindidField;
            }
            set {
                this.kindidField = value;
            }
        }
        
        /// <remarks/>
        public int TransType {
            get {
                return this.transTypeField;
            }
            set {
                this.transTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TransCode {
            get {
                return this.transCodeField;
            }
            set {
                this.transCodeField = value;
            }
        }
        
        /// <remarks/>
        public long OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public long OrderDtlID {
            get {
                return this.orderDtlIDField;
            }
            set {
                this.orderDtlIDField = value;
            }
        }
        
        /// <remarks/>
        public long DSRID {
            get {
                return this.dSRIDField;
            }
            set {
                this.dSRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class PackingListDetail {
        
        private long packingListHeaderIDField;
        
        private long packingListDTLIDField;
        
        private long itemIDField;
        
        private long lotIDField;
        
        private string itemCodeField;
        
        private string lotCodeField;
        
        private decimal itemQTYprimaryField;
        
        private decimal itemQTYsecondaryField;
        
        private int itemMunitPrimaryField;
        
        private int itemMunitSecondaryField;
        
        private string colorField;
        
        private string draftField;
        
        private decimal widthField;
        
        private decimal lengthField;
        
        /// <remarks/>
        public long PackingListHeaderID {
            get {
                return this.packingListHeaderIDField;
            }
            set {
                this.packingListHeaderIDField = value;
            }
        }
        
        /// <remarks/>
        public long PackingListDTLID {
            get {
                return this.packingListDTLIDField;
            }
            set {
                this.packingListDTLIDField = value;
            }
        }
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public long LotID {
            get {
                return this.lotIDField;
            }
            set {
                this.lotIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LotCode {
            get {
                return this.lotCodeField;
            }
            set {
                this.lotCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemQTYprimary {
            get {
                return this.itemQTYprimaryField;
            }
            set {
                this.itemQTYprimaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemQTYsecondary {
            get {
                return this.itemQTYsecondaryField;
            }
            set {
                this.itemQTYsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public int ItemMunitPrimary {
            get {
                return this.itemMunitPrimaryField;
            }
            set {
                this.itemMunitPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public int ItemMunitSecondary {
            get {
                return this.itemMunitSecondaryField;
            }
            set {
                this.itemMunitSecondaryField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Draft {
            get {
                return this.draftField;
            }
            set {
                this.draftField = value;
            }
        }
        
        /// <remarks/>
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class SyncLot {
        
        private long lotIDField;
        
        private long itemIDField;
        
        private short compIDField;
        
        private short branchIDField;
        
        private short storeIDField;
        
        private string lotCodeField;
        
        private decimal widthField;
        
        private decimal lengthField;
        
        private string colorField;
        
        private string draftField;
        
        private decimal itemPrimaryQtyField;
        
        private decimal itemSecondaryQtyField;
        
        private string entryDateField;
        
        /// <remarks/>
        public long LotID {
            get {
                return this.lotIDField;
            }
            set {
                this.lotIDField = value;
            }
        }
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public short CompID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public short BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public short StoreID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string LotCode {
            get {
                return this.lotCodeField;
            }
            set {
                this.lotCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Draft {
            get {
                return this.draftField;
            }
            set {
                this.draftField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemPrimaryQty {
            get {
                return this.itemPrimaryQtyField;
            }
            set {
                this.itemPrimaryQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemSecondaryQty {
            get {
                return this.itemSecondaryQtyField;
            }
            set {
                this.itemSecondaryQtyField = value;
            }
        }
        
        /// <remarks/>
        public string EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class SyncInfo {
        
        private long minItemIDField;
        
        private long maxItemIDField;
        
        private long minItemRowidField;
        
        private long maxItemRowidField;
        
        private long itemsRowsCountField;
        
        private long minLotIDField;
        
        private long maxLotIDField;
        
        private long minLotRowIDField;
        
        private long maxLotRowIDField;
        
        private long lotRowsCountField;
        
        private string commentsField;
        
        /// <remarks/>
        public long MinItemID {
            get {
                return this.minItemIDField;
            }
            set {
                this.minItemIDField = value;
            }
        }
        
        /// <remarks/>
        public long MaxItemID {
            get {
                return this.maxItemIDField;
            }
            set {
                this.maxItemIDField = value;
            }
        }
        
        /// <remarks/>
        public long MinItemRowid {
            get {
                return this.minItemRowidField;
            }
            set {
                this.minItemRowidField = value;
            }
        }
        
        /// <remarks/>
        public long MaxItemRowid {
            get {
                return this.maxItemRowidField;
            }
            set {
                this.maxItemRowidField = value;
            }
        }
        
        /// <remarks/>
        public long ItemsRowsCount {
            get {
                return this.itemsRowsCountField;
            }
            set {
                this.itemsRowsCountField = value;
            }
        }
        
        /// <remarks/>
        public long MinLotID {
            get {
                return this.minLotIDField;
            }
            set {
                this.minLotIDField = value;
            }
        }
        
        /// <remarks/>
        public long MaxLotID {
            get {
                return this.maxLotIDField;
            }
            set {
                this.maxLotIDField = value;
            }
        }
        
        /// <remarks/>
        public long MinLotRowID {
            get {
                return this.minLotRowIDField;
            }
            set {
                this.minLotRowIDField = value;
            }
        }
        
        /// <remarks/>
        public long MaxLotRowID {
            get {
                return this.maxLotRowIDField;
            }
            set {
                this.maxLotRowIDField = value;
            }
        }
        
        /// <remarks/>
        public long LotRowsCount {
            get {
                return this.lotRowsCountField;
            }
            set {
                this.lotRowsCountField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class SyncERPItem {
        
        private long itemIDField;
        
        private short compIDField;
        
        private short branchIDField;
        
        private short storeIDField;
        
        private string itemCodeField;
        
        private string itemDescField;
        
        private int mUnitPrimaryField;
        
        private int mUnitSecondaryField;
        
        private decimal mUnitsRelationField;
        
        private string mUnitDesc1Field;
        
        private string mUnitDesc2Field;
        
        private string entryDateField;
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public short CompID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public short BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public short StoreID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
            }
        }
        
        /// <remarks/>
        public int MUnitPrimary {
            get {
                return this.mUnitPrimaryField;
            }
            set {
                this.mUnitPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public int MUnitSecondary {
            get {
                return this.mUnitSecondaryField;
            }
            set {
                this.mUnitSecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal MUnitsRelation {
            get {
                return this.mUnitsRelationField;
            }
            set {
                this.mUnitsRelationField = value;
            }
        }
        
        /// <remarks/>
        public string MUnitDesc1 {
            get {
                return this.mUnitDesc1Field;
            }
            set {
                this.mUnitDesc1Field = value;
            }
        }
        
        /// <remarks/>
        public string MUnitDesc2 {
            get {
                return this.mUnitDesc2Field;
            }
            set {
                this.mUnitDesc2Field = value;
            }
        }
        
        /// <remarks/>
        public string EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class TransCodeDetail {
        
        private long ftrIDField;
        
        private long transIDField;
        
        private long receiveIDField;
        
        private long itemIDField;
        
        private long lotIDField;
        
        private int munitprimaryField;
        
        private int munitsecondaryField;
        
        private decimal itemQtyPrimaryField;
        
        private decimal itemQtySecondaryField;
        
        private decimal zwidthField;
        
        private decimal zlengthField;
        
        private string zcolorField;
        
        private string zdraftField;
        
        private string lotcodeField;
        
        private string itemcodeField;
        
        private string itemdescField;
        
        /// <remarks/>
        public long FtrID {
            get {
                return this.ftrIDField;
            }
            set {
                this.ftrIDField = value;
            }
        }
        
        /// <remarks/>
        public long TransID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
            }
        }
        
        /// <remarks/>
        public long ReceiveID {
            get {
                return this.receiveIDField;
            }
            set {
                this.receiveIDField = value;
            }
        }
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public long LotID {
            get {
                return this.lotIDField;
            }
            set {
                this.lotIDField = value;
            }
        }
        
        /// <remarks/>
        public int munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public int munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemQtyPrimary {
            get {
                return this.itemQtyPrimaryField;
            }
            set {
                this.itemQtyPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemQtySecondary {
            get {
                return this.itemQtySecondaryField;
            }
            set {
                this.itemQtySecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal Zwidth {
            get {
                return this.zwidthField;
            }
            set {
                this.zwidthField = value;
            }
        }
        
        /// <remarks/>
        public decimal Zlength {
            get {
                return this.zlengthField;
            }
            set {
                this.zlengthField = value;
            }
        }
        
        /// <remarks/>
        public string zcolor {
            get {
                return this.zcolorField;
            }
            set {
                this.zcolorField = value;
            }
        }
        
        /// <remarks/>
        public string zdraft {
            get {
                return this.zdraftField;
            }
            set {
                this.zdraftField = value;
            }
        }
        
        /// <remarks/>
        public string lotcode {
            get {
                return this.lotcodeField;
            }
            set {
                this.lotcodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class TransCodeHeader {
        
        private long ftrIDField;
        
        private short compidField;
        
        private short branchidField;
        
        private string tradecodeField;
        
        private int fromstoreidField;
        
        private int tostoreidField;
        
        private string branchnameField;
        
        private string transdateField;
        
        /// <remarks/>
        public long FtrID {
            get {
                return this.ftrIDField;
            }
            set {
                this.ftrIDField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public string tradecode {
            get {
                return this.tradecodeField;
            }
            set {
                this.tradecodeField = value;
            }
        }
        
        /// <remarks/>
        public int fromstoreid {
            get {
                return this.fromstoreidField;
            }
            set {
                this.fromstoreidField = value;
            }
        }
        
        /// <remarks/>
        public int tostoreid {
            get {
                return this.tostoreidField;
            }
            set {
                this.tostoreidField = value;
            }
        }
        
        /// <remarks/>
        public string branchname {
            get {
                return this.branchnameField;
            }
            set {
                this.branchnameField = value;
            }
        }
        
        /// <remarks/>
        public string transdate {
            get {
                return this.transdateField;
            }
            set {
                this.transdateField = value;
            }
        }
    }
}
