//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9179.
// 
namespace WMSMobileClient.WMSservice {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://10.1.10.46/WMSMiniWebService/WebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDBConnection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckDBConnection() {
            object[] results = this.Invoke("CheckDBConnection", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckDBConnection(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckDBConnection", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckDBConnection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ItemInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TItems ItemInfo(long itemid) {
            object[] results = this.Invoke("ItemInfo", new object[] {
                        itemid});
            return ((TItems)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginItemInfo(long itemid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ItemInfo", new object[] {
                        itemid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TItems EndItemInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TItems)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOpenReceivesList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOpenReceivesList(short branchid) {
            object[] results = this.Invoke("GetOpenReceivesList", new object[] {
                        branchid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOpenReceivesList(short branchid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOpenReceivesList", new object[] {
                        branchid}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetOpenReceivesList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewReceivesTranscode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long InsertNewReceivesTranscode(TransCodeHeader thistranscode) {
            object[] results = this.Invoke("InsertNewReceivesTranscode", new object[] {
                        thistranscode});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertNewReceivesTranscode(TransCodeHeader thistranscode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertNewReceivesTranscode", new object[] {
                        thistranscode}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndInsertNewReceivesTranscode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ItemInfoByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TItems ItemInfoByCode(string itemcode) {
            object[] results = this.Invoke("ItemInfoByCode", new object[] {
                        itemcode});
            return ((TItems)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginItemInfoByCode(string itemcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ItemInfoByCode", new object[] {
                        itemcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public TItems EndItemInfoByCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TItems)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TItemLot LotInfo(long lotid) {
            object[] results = this.Invoke("LotInfo", new object[] {
                        lotid});
            return ((TItemLot)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLotInfo(long lotid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LotInfo", new object[] {
                        lotid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TItemLot EndLotInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TItemLot)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtlSyncItemsAndLots", RequestNamespace="http://tempuri.org/", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtlSyncItemsAndLots() {
            this.Invoke("AtlSyncItemsAndLots", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAtlSyncItemsAndLots(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AtlSyncItemsAndLots", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAtlSyncItemsAndLots(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtlDetailsQtyFromWmsMiniDB", RequestNamespace="http://tempuri.org/", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtlDetailsQtyFromWmsMiniDB(short branchid, short storeid, short comid) {
            this.Invoke("AtlDetailsQtyFromWmsMiniDB", new object[] {
                        branchid,
                        storeid,
                        comid});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAtlDetailsQtyFromWmsMiniDB(short branchid, short storeid, short comid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AtlDetailsQtyFromWmsMiniDB", new object[] {
                        branchid,
                        storeid,
                        comid}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAtlDetailsQtyFromWmsMiniDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TESTGetDetailsQtyFromWmsMiniDB", RequestNamespace="http://tempuri.org/", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TESTGetDetailsQtyFromWmsMiniDB(short branchid, short storeid, short comid) {
            this.Invoke("TESTGetDetailsQtyFromWmsMiniDB", new object[] {
                        branchid,
                        storeid,
                        comid});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTESTGetDetailsQtyFromWmsMiniDB(short branchid, short storeid, short comid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TESTGetDetailsQtyFromWmsMiniDB", new object[] {
                        branchid,
                        storeid,
                        comid}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndTESTGetDetailsQtyFromWmsMiniDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtlGeInventoryNow", RequestNamespace="http://tempuri.org/", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtlGeInventoryNow(int branchid, bool forcedelete) {
            this.Invoke("AtlGeInventoryNow", new object[] {
                        branchid,
                        forcedelete});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAtlGeInventoryNow(int branchid, bool forcedelete, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AtlGeInventoryNow", new object[] {
                        branchid,
                        forcedelete}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAtlGeInventoryNow(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtlGeInventory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long AtlGeInventory(int branchid, bool forcedelete) {
            object[] results = this.Invoke("AtlGeInventory", new object[] {
                        branchid,
                        forcedelete});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAtlGeInventory(int branchid, bool forcedelete, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AtlGeInventory", new object[] {
                        branchid,
                        forcedelete}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndAtlGeInventory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotInfoByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TItemLot LotInfoByCode(string lotcode, long itemid) {
            object[] results = this.Invoke("LotInfoByCode", new object[] {
                        lotcode,
                        itemid});
            return ((TItemLot)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLotInfoByCode(string lotcode, long itemid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LotInfoByCode", new object[] {
                        lotcode,
                        itemid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TItemLot EndLotInfoByCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TItemLot)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemPartial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetItemPartial(long startid, long endid) {
            object[] results = this.Invoke("GetItemPartial", new object[] {
                        startid,
                        endid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemPartial(long startid, long endid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemPartial", new object[] {
                        startid,
                        endid}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetItemPartial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemLotPartial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetItemLotPartial(long startid, long endid) {
            object[] results = this.Invoke("GetItemLotPartial", new object[] {
                        startid,
                        endid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemLotPartial(long startid, long endid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemLotPartial", new object[] {
                        startid,
                        endid}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetItemLotPartial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncERPItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SyncERPItems() {
            object[] results = this.Invoke("SyncERPItems", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSyncERPItems(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SyncERPItems", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndSyncERPItems(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportInventoryHeaderCType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportInventoryHeaderCType(TInventoryHeader invhdr) {
            object[] results = this.Invoke("ImportInventoryHeaderCType", new object[] {
                        invhdr});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportInventoryHeaderCType(TInventoryHeader invhdr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportInventoryHeaderCType", new object[] {
                        invhdr}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportInventoryHeaderCType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportInventory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportInventory(System.Data.DataSet ds) {
            object[] results = this.Invoke("ImportInventory", new object[] {
                        ds});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportInventory(System.Data.DataSet ds, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportInventory", new object[] {
                        ds}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportInventory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ItemExists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ItemExists(long itemid) {
            object[] results = this.Invoke("ItemExists", new object[] {
                        itemid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginItemExists(long itemid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ItemExists", new object[] {
                        itemid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndItemExists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LotExists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long LotExists(long lotid) {
            object[] results = this.Invoke("LotExists", new object[] {
                        lotid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLotExists(long lotid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LotExists", new object[] {
                        lotid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndLotExists(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long InsertNewItem(ERPItem newitem) {
            object[] results = this.Invoke("InsertNewItem", new object[] {
                        newitem});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertNewItem(ERPItem newitem, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertNewItem", new object[] {
                        newitem}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndInsertNewItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewLot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long InsertNewLot(ERPLot newlot) {
            object[] results = this.Invoke("InsertNewLot", new object[] {
                        newlot});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertNewLot(ERPLot newlot, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertNewLot", new object[] {
                        newlot}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndInsertNewLot(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportInventoryOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportInventoryOnline(TInventory inv) {
            object[] results = this.Invoke("ImportInventoryOnline", new object[] {
                        inv});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportInventoryOnline(TInventory inv, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportInventoryOnline", new object[] {
                        inv}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportInventoryOnline(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportInventoryCTypeList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportInventoryCTypeList(TInventory[] inv, bool clearprevious) {
            object[] results = this.Invoke("ImportInventoryCTypeList", new object[] {
                        inv,
                        clearprevious});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportInventoryCTypeList(TInventory[] inv, bool clearprevious, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportInventoryCTypeList", new object[] {
                        inv,
                        clearprevious}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportInventoryCTypeList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportInventoryCType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportInventoryCType(TInventory[] inv, bool clearprevious) {
            object[] results = this.Invoke("ImportInventoryCType", new object[] {
                        inv,
                        clearprevious});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportInventoryCType(TInventory[] inv, bool clearprevious, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportInventoryCType", new object[] {
                        inv,
                        clearprevious}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportInventoryCType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportInventoryAlter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportInventoryAlter(TInventory inv, bool clearprevious) {
            object[] results = this.Invoke("ImportInventoryAlter", new object[] {
                        inv,
                        clearprevious});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportInventoryAlter(TInventory inv, bool clearprevious, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportInventoryAlter", new object[] {
                        inv,
                        clearprevious}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndImportInventoryAlter(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sqlerrorlog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long Sqlerrorlog() {
            object[] results = this.Invoke("Sqlerrorlog", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSqlerrorlog(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Sqlerrorlog", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndSqlerrorlog(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemMunits", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetItemMunits() {
            object[] results = this.Invoke("GetItemMunits", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemMunits(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemMunits", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetItemMunits(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSyncInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SyncInfo GetSyncInfo() {
            object[] results = this.Invoke("GetSyncInfo", new object[0]);
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSyncInfo(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSyncInfo", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SyncInfo EndGetSyncInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SyncInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SOA_GetStores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SOA_GetStores() {
            object[] results = this.Invoke("SOA_GetStores", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetStores(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetStores", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSOA_GetStores(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadInventoryStatusCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultWithMessage UploadInventoryStatusCheck(TInventoryHeader invhdr) {
            object[] results = this.Invoke("UploadInventoryStatusCheck", new object[] {
                        invhdr});
            return ((ResultWithMessage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadInventoryStatusCheck(TInventoryHeader invhdr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadInventoryStatusCheck", new object[] {
                        invhdr}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResultWithMessage EndUploadInventoryStatusCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResultWithMessage)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SOA_GetItemsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERPItem[] SOA_GetItemsList(int storeid, long startindex, long endindex) {
            object[] results = this.Invoke("SOA_GetItemsList", new object[] {
                        storeid,
                        startindex,
                        endindex});
            return ((ERPItem[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetItemsList(int storeid, long startindex, long endindex, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetItemsList", new object[] {
                        storeid,
                        startindex,
                        endindex}, callback, asyncState);
        }
        
        /// <remarks/>
        public ERPItem[] EndSOA_GetItemsList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ERPItem[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SOA_GetLotsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ERPLot[] SOA_GetLotsList(int storeid, long startindex, long endindex) {
            object[] results = this.Invoke("SOA_GetLotsList", new object[] {
                        storeid,
                        startindex,
                        endindex});
            return ((ERPLot[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetLotsList(int storeid, long startindex, long endindex, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetLotsList", new object[] {
                        storeid,
                        startindex,
                        endindex}, callback, asyncState);
        }
        
        /// <remarks/>
        public ERPLot[] EndSOA_GetLotsList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ERPLot[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Clearitemlist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long Clearitemlist() {
            object[] results = this.Invoke("Clearitemlist", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearitemlist(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Clearitemlist", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndClearitemlist(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Clearlotlist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long Clearlotlist() {
            object[] results = this.Invoke("Clearlotlist", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearlotlist(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Clearlotlist", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndClearlotlist(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertTransCodeDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertTransCodeDetails(TransCodeDetail[] ldtl) {
            object[] results = this.Invoke("InsertTransCodeDetails", new object[] {
                        ldtl});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertTransCodeDetails(TransCodeDetail[] ldtl, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertTransCodeDetails", new object[] {
                        ldtl}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndInsertTransCodeDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertTransCodeHeader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long InsertTransCodeHeader(TransCodeHeader t) {
            object[] results = this.Invoke("InsertTransCodeHeader", new object[] {
                        t});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertTransCodeHeader(TransCodeHeader t, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertTransCodeHeader", new object[] {
                        t}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndInsertTransCodeHeader(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SOA_GetLots", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SOA_GetLots(int storeid, long startid, long endid) {
            object[] results = this.Invoke("SOA_GetLots", new object[] {
                        storeid,
                        startid,
                        endid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetLots(int storeid, long startid, long endid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetLots", new object[] {
                        storeid,
                        startid,
                        endid}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSOA_GetLots(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SOA_GetERPLotSecondQTY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal SOA_GetERPLotSecondQTY(long lotid, int branchid) {
            object[] results = this.Invoke("SOA_GetERPLotSecondQTY", new object[] {
                        lotid,
                        branchid});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSOA_GetERPLotSecondQTY(long lotid, int branchid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SOA_GetERPLotSecondQTY", new object[] {
                        lotid,
                        branchid}, callback, asyncState);
        }
        
        /// <remarks/>
        public decimal EndSOA_GetERPLotSecondQTY(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransCodeDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransCodeDetail GetTransCodeDetails(string zbarcode) {
            object[] results = this.Invoke("GetTransCodeDetails", new object[] {
                        zbarcode});
            return ((TransCodeDetail)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTransCodeDetails(string zbarcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTransCodeDetails", new object[] {
                        zbarcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public TransCodeDetail EndGetTransCodeDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransCodeDetail)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertIntoReceives", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable InsertIntoReceives(TransCodeDetail treceive) {
            object[] results = this.Invoke("InsertIntoReceives", new object[] {
                        treceive});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertIntoReceives(TransCodeDetail treceive, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertIntoReceives", new object[] {
                        treceive}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndInsertIntoReceives(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransRemains", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTransRemains(long ftrid) {
            object[] results = this.Invoke("GetTransRemains", new object[] {
                        ftrid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTransRemains(long ftrid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTransRemains", new object[] {
                        ftrid}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetTransRemains(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInventoryTasks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetInventoryTasks(int branchid) {
            object[] results = this.Invoke("GetInventoryTasks", new object[] {
                        branchid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryTasks(int branchid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventoryTasks", new object[] {
                        branchid}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetInventoryTasks(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TItems {
        
        private long itemidField;
        
        private short compidField;
        
        private string itemcodeField;
        
        private long productidField;
        
        private string itemdescField;
        
        private int groupitemidField;
        
        private int mainitemcatidField;
        
        private int subitemcatidField;
        
        private int manufactureidField;
        
        private decimal stocklevelqtyField;
        
        private decimal stocklevelmunitField;
        
        private short munitprimaryField;
        
        private string munitprimarydescrField;
        
        private short munitprimarydecimalsField;
        
        private short munitsecondaryField;
        
        private string munitsecondarydescrField;
        
        private short munitsecondarydecimalsField;
        
        private decimal munitsrelationField;
        
        private short munitputawayField;
        
        private decimal munitsputawayrelationField;
        
        private short munitweightField;
        
        private decimal munitweightrelationField;
        
        private int wmszoneField;
        
        private short replenishmenttypeField;
        
        private long erpitemidField;
        
        private string erpitemcodeField;
        
        private int accountclassidField;
        
        private bool haslengthField;
        
        private bool hascolorField;
        
        private long stocklevelqtywcolorField;
        
        private decimal replitemlengthField;
        
        private decimal standardlengthField;
        
        private bool enabledField;
        
        private bool autoprodscheduleField;
        
        private string dimensionsField;
        
        private string dbreccreatedateField;
        
        private int dbreccreateuserField;
        
        private string dbreccreatehostField;
        
        private string dbrecmoddateField;
        
        private int dbrecmoduserField;
        
        private string dbrecmodhostField;
        
        /// <remarks/>
        public long itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public long productid {
            get {
                return this.productidField;
            }
            set {
                this.productidField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
        
        /// <remarks/>
        public int groupitemid {
            get {
                return this.groupitemidField;
            }
            set {
                this.groupitemidField = value;
            }
        }
        
        /// <remarks/>
        public int mainitemcatid {
            get {
                return this.mainitemcatidField;
            }
            set {
                this.mainitemcatidField = value;
            }
        }
        
        /// <remarks/>
        public int subitemcatid {
            get {
                return this.subitemcatidField;
            }
            set {
                this.subitemcatidField = value;
            }
        }
        
        /// <remarks/>
        public int manufactureid {
            get {
                return this.manufactureidField;
            }
            set {
                this.manufactureidField = value;
            }
        }
        
        /// <remarks/>
        public decimal stocklevelqty {
            get {
                return this.stocklevelqtyField;
            }
            set {
                this.stocklevelqtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal stocklevelmunit {
            get {
                return this.stocklevelmunitField;
            }
            set {
                this.stocklevelmunitField = value;
            }
        }
        
        /// <remarks/>
        public short munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public string munitprimarydescr {
            get {
                return this.munitprimarydescrField;
            }
            set {
                this.munitprimarydescrField = value;
            }
        }
        
        /// <remarks/>
        public short munitprimarydecimals {
            get {
                return this.munitprimarydecimalsField;
            }
            set {
                this.munitprimarydecimalsField = value;
            }
        }
        
        /// <remarks/>
        public short munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public string munitsecondarydescr {
            get {
                return this.munitsecondarydescrField;
            }
            set {
                this.munitsecondarydescrField = value;
            }
        }
        
        /// <remarks/>
        public short munitsecondarydecimals {
            get {
                return this.munitsecondarydecimalsField;
            }
            set {
                this.munitsecondarydecimalsField = value;
            }
        }
        
        /// <remarks/>
        public decimal munitsrelation {
            get {
                return this.munitsrelationField;
            }
            set {
                this.munitsrelationField = value;
            }
        }
        
        /// <remarks/>
        public short munitputaway {
            get {
                return this.munitputawayField;
            }
            set {
                this.munitputawayField = value;
            }
        }
        
        /// <remarks/>
        public decimal munitsputawayrelation {
            get {
                return this.munitsputawayrelationField;
            }
            set {
                this.munitsputawayrelationField = value;
            }
        }
        
        /// <remarks/>
        public short munitweight {
            get {
                return this.munitweightField;
            }
            set {
                this.munitweightField = value;
            }
        }
        
        /// <remarks/>
        public decimal munitweightrelation {
            get {
                return this.munitweightrelationField;
            }
            set {
                this.munitweightrelationField = value;
            }
        }
        
        /// <remarks/>
        public int wmszone {
            get {
                return this.wmszoneField;
            }
            set {
                this.wmszoneField = value;
            }
        }
        
        /// <remarks/>
        public short replenishmenttype {
            get {
                return this.replenishmenttypeField;
            }
            set {
                this.replenishmenttypeField = value;
            }
        }
        
        /// <remarks/>
        public long erpitemid {
            get {
                return this.erpitemidField;
            }
            set {
                this.erpitemidField = value;
            }
        }
        
        /// <remarks/>
        public string erpitemcode {
            get {
                return this.erpitemcodeField;
            }
            set {
                this.erpitemcodeField = value;
            }
        }
        
        /// <remarks/>
        public int accountclassid {
            get {
                return this.accountclassidField;
            }
            set {
                this.accountclassidField = value;
            }
        }
        
        /// <remarks/>
        public bool haslength {
            get {
                return this.haslengthField;
            }
            set {
                this.haslengthField = value;
            }
        }
        
        /// <remarks/>
        public bool hascolor {
            get {
                return this.hascolorField;
            }
            set {
                this.hascolorField = value;
            }
        }
        
        /// <remarks/>
        public long stocklevelqtywcolor {
            get {
                return this.stocklevelqtywcolorField;
            }
            set {
                this.stocklevelqtywcolorField = value;
            }
        }
        
        /// <remarks/>
        public decimal replitemlength {
            get {
                return this.replitemlengthField;
            }
            set {
                this.replitemlengthField = value;
            }
        }
        
        /// <remarks/>
        public decimal standardlength {
            get {
                return this.standardlengthField;
            }
            set {
                this.standardlengthField = value;
            }
        }
        
        /// <remarks/>
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public bool autoprodschedule {
            get {
                return this.autoprodscheduleField;
            }
            set {
                this.autoprodscheduleField = value;
            }
        }
        
        /// <remarks/>
        public string dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatedate {
            get {
                return this.dbreccreatedateField;
            }
            set {
                this.dbreccreatedateField = value;
            }
        }
        
        /// <remarks/>
        public int dbreccreateuser {
            get {
                return this.dbreccreateuserField;
            }
            set {
                this.dbreccreateuserField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatehost {
            get {
                return this.dbreccreatehostField;
            }
            set {
                this.dbreccreatehostField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmoddate {
            get {
                return this.dbrecmoddateField;
            }
            set {
                this.dbrecmoddateField = value;
            }
        }
        
        /// <remarks/>
        public int dbrecmoduser {
            get {
                return this.dbrecmoduserField;
            }
            set {
                this.dbrecmoduserField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmodhost {
            get {
                return this.dbrecmodhostField;
            }
            set {
                this.dbrecmodhostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class TransCodeDetail {
        
        private long ftrIDField;
        
        private long transIDField;
        
        private long receiveIDField;
        
        private long itemIDField;
        
        private long lotIDField;
        
        private int munitprimaryField;
        
        private int munitsecondaryField;
        
        private decimal itemQtyPrimaryField;
        
        private decimal itemQtySecondaryField;
        
        private decimal zwidthField;
        
        private decimal zlengthField;
        
        private string zcolorField;
        
        private string zdraftField;
        
        private string lotcodeField;
        
        private string itemcodeField;
        
        private string itemdescField;
        
        /// <remarks/>
        public long FtrID {
            get {
                return this.ftrIDField;
            }
            set {
                this.ftrIDField = value;
            }
        }
        
        /// <remarks/>
        public long TransID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
            }
        }
        
        /// <remarks/>
        public long ReceiveID {
            get {
                return this.receiveIDField;
            }
            set {
                this.receiveIDField = value;
            }
        }
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public long LotID {
            get {
                return this.lotIDField;
            }
            set {
                this.lotIDField = value;
            }
        }
        
        /// <remarks/>
        public int munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public int munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemQtyPrimary {
            get {
                return this.itemQtyPrimaryField;
            }
            set {
                this.itemQtyPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemQtySecondary {
            get {
                return this.itemQtySecondaryField;
            }
            set {
                this.itemQtySecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal Zwidth {
            get {
                return this.zwidthField;
            }
            set {
                this.zwidthField = value;
            }
        }
        
        /// <remarks/>
        public decimal Zlength {
            get {
                return this.zlengthField;
            }
            set {
                this.zlengthField = value;
            }
        }
        
        /// <remarks/>
        public string zcolor {
            get {
                return this.zcolorField;
            }
            set {
                this.zcolorField = value;
            }
        }
        
        /// <remarks/>
        public string zdraft {
            get {
                return this.zdraftField;
            }
            set {
                this.zdraftField = value;
            }
        }
        
        /// <remarks/>
        public string lotcode {
            get {
                return this.lotcodeField;
            }
            set {
                this.lotcodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultWithMessage {
        
        private bool posresultField;
        
        private long resultnoField;
        
        private string successmessageField;
        
        private string errormessageField;
        
        /// <remarks/>
        public bool posresult {
            get {
                return this.posresultField;
            }
            set {
                this.posresultField = value;
            }
        }
        
        /// <remarks/>
        public long resultno {
            get {
                return this.resultnoField;
            }
            set {
                this.resultnoField = value;
            }
        }
        
        /// <remarks/>
        public string successmessage {
            get {
                return this.successmessageField;
            }
            set {
                this.successmessageField = value;
            }
        }
        
        /// <remarks/>
        public string errormessage {
            get {
                return this.errormessageField;
            }
            set {
                this.errormessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SyncInfo {
        
        private long minItemIDField;
        
        private long maxItemIDField;
        
        private long itemsRowsCountField;
        
        private long minLotIDField;
        
        private long maxLotIDField;
        
        private long lotRowsCountField;
        
        private string commentsField;
        
        /// <remarks/>
        public long MinItemID {
            get {
                return this.minItemIDField;
            }
            set {
                this.minItemIDField = value;
            }
        }
        
        /// <remarks/>
        public long MaxItemID {
            get {
                return this.maxItemIDField;
            }
            set {
                this.maxItemIDField = value;
            }
        }
        
        /// <remarks/>
        public long ItemsRowsCount {
            get {
                return this.itemsRowsCountField;
            }
            set {
                this.itemsRowsCountField = value;
            }
        }
        
        /// <remarks/>
        public long MinLotID {
            get {
                return this.minLotIDField;
            }
            set {
                this.minLotIDField = value;
            }
        }
        
        /// <remarks/>
        public long MaxLotID {
            get {
                return this.maxLotIDField;
            }
            set {
                this.maxLotIDField = value;
            }
        }
        
        /// <remarks/>
        public long LotRowsCount {
            get {
                return this.lotRowsCountField;
            }
            set {
                this.lotRowsCountField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TInventory {
        
        private long invIDField;
        
        private short compIDField;
        
        private short branchIDField;
        
        private int storeIDField;
        
        private long invHdrIDField;
        
        private long invHdrIDServerField;
        
        private long itemIDField;
        
        private string itemCodeField;
        
        private long lotIDField;
        
        private string lotCodeField;
        
        private string invDateField;
        
        private short mUnitPrimaryField;
        
        private decimal invQtyField;
        
        private decimal eRPQtyField;
        
        private short mUnitSecondaryField;
        
        private decimal invQtySecondaryField;
        
        private string serialNumberField;
        
        private long mobInvIDField;
        
        /// <remarks/>
        public long InvID {
            get {
                return this.invIDField;
            }
            set {
                this.invIDField = value;
            }
        }
        
        /// <remarks/>
        public short CompID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public short BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public int StoreID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public long InvHdrID {
            get {
                return this.invHdrIDField;
            }
            set {
                this.invHdrIDField = value;
            }
        }
        
        /// <remarks/>
        public long InvHdrIDServer {
            get {
                return this.invHdrIDServerField;
            }
            set {
                this.invHdrIDServerField = value;
            }
        }
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public long LotID {
            get {
                return this.lotIDField;
            }
            set {
                this.lotIDField = value;
            }
        }
        
        /// <remarks/>
        public string LotCode {
            get {
                return this.lotCodeField;
            }
            set {
                this.lotCodeField = value;
            }
        }
        
        /// <remarks/>
        public string InvDate {
            get {
                return this.invDateField;
            }
            set {
                this.invDateField = value;
            }
        }
        
        /// <remarks/>
        public short MUnitPrimary {
            get {
                return this.mUnitPrimaryField;
            }
            set {
                this.mUnitPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal InvQty {
            get {
                return this.invQtyField;
            }
            set {
                this.invQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ERPQty {
            get {
                return this.eRPQtyField;
            }
            set {
                this.eRPQtyField = value;
            }
        }
        
        /// <remarks/>
        public short MUnitSecondary {
            get {
                return this.mUnitSecondaryField;
            }
            set {
                this.mUnitSecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal InvQtySecondary {
            get {
                return this.invQtySecondaryField;
            }
            set {
                this.invQtySecondaryField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public long MobInvID {
            get {
                return this.mobInvIDField;
            }
            set {
                this.mobInvIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ERPLot {
        
        private long lotIDField;
        
        private long itemIDField;
        
        private short compIDField;
        
        private string lotCodeField;
        
        private decimal widthField;
        
        private decimal lengthField;
        
        private string colorField;
        
        private string draftField;
        
        private decimal itemPrimaryQtyField;
        
        private decimal itemSecondaryQtyField;
        
        private string entryDateField;
        
        /// <remarks/>
        public long LotID {
            get {
                return this.lotIDField;
            }
            set {
                this.lotIDField = value;
            }
        }
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public short CompID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public string LotCode {
            get {
                return this.lotCodeField;
            }
            set {
                this.lotCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Draft {
            get {
                return this.draftField;
            }
            set {
                this.draftField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemPrimaryQty {
            get {
                return this.itemPrimaryQtyField;
            }
            set {
                this.itemPrimaryQtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemSecondaryQty {
            get {
                return this.itemSecondaryQtyField;
            }
            set {
                this.itemSecondaryQtyField = value;
            }
        }
        
        /// <remarks/>
        public string EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ERPItem {
        
        private long itemIDField;
        
        private short compIDField;
        
        private string itemCodeField;
        
        private string itemDescField;
        
        private int mUnitPrimaryField;
        
        private int mUnitSecondaryField;
        
        private decimal mUnitsRelationField;
        
        private string mUnitDesc1Field;
        
        private string mUnitDesc2Field;
        
        private string entryDateField;
        
        /// <remarks/>
        public long ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public short CompID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
            }
        }
        
        /// <remarks/>
        public int MUnitPrimary {
            get {
                return this.mUnitPrimaryField;
            }
            set {
                this.mUnitPrimaryField = value;
            }
        }
        
        /// <remarks/>
        public int MUnitSecondary {
            get {
                return this.mUnitSecondaryField;
            }
            set {
                this.mUnitSecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal MUnitsRelation {
            get {
                return this.mUnitsRelationField;
            }
            set {
                this.mUnitsRelationField = value;
            }
        }
        
        /// <remarks/>
        public string MUnitDesc1 {
            get {
                return this.mUnitDesc1Field;
            }
            set {
                this.mUnitDesc1Field = value;
            }
        }
        
        /// <remarks/>
        public string MUnitDesc2 {
            get {
                return this.mUnitDesc2Field;
            }
            set {
                this.mUnitDesc2Field = value;
            }
        }
        
        /// <remarks/>
        public string EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TInventoryHeader {
        
        private long invHdrIDField;
        
        private short compIDField;
        
        private short branchidField;
        
        private int storeidField;
        
        private string storeNameField;
        
        private string invDateField;
        
        private short invTypeField;
        
        private string invCommentsField;
        
        private short confirmedField;
        
        private long customerIDField;
        
        private short invStatusField;
        
        private string customerTitleField;
        
        private long mobInvHdrIDField;
        
        private long invSyncIDField;
        
        /// <remarks/>
        public long InvHdrID {
            get {
                return this.invHdrIDField;
            }
            set {
                this.invHdrIDField = value;
            }
        }
        
        /// <remarks/>
        public short CompID {
            get {
                return this.compIDField;
            }
            set {
                this.compIDField = value;
            }
        }
        
        /// <remarks/>
        public short Branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public int Storeid {
            get {
                return this.storeidField;
            }
            set {
                this.storeidField = value;
            }
        }
        
        /// <remarks/>
        public string StoreName {
            get {
                return this.storeNameField;
            }
            set {
                this.storeNameField = value;
            }
        }
        
        /// <remarks/>
        public string InvDate {
            get {
                return this.invDateField;
            }
            set {
                this.invDateField = value;
            }
        }
        
        /// <remarks/>
        public short InvType {
            get {
                return this.invTypeField;
            }
            set {
                this.invTypeField = value;
            }
        }
        
        /// <remarks/>
        public string InvComments {
            get {
                return this.invCommentsField;
            }
            set {
                this.invCommentsField = value;
            }
        }
        
        /// <remarks/>
        public short Confirmed {
            get {
                return this.confirmedField;
            }
            set {
                this.confirmedField = value;
            }
        }
        
        /// <remarks/>
        public long CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public short InvStatus {
            get {
                return this.invStatusField;
            }
            set {
                this.invStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerTitle {
            get {
                return this.customerTitleField;
            }
            set {
                this.customerTitleField = value;
            }
        }
        
        /// <remarks/>
        public long MobInvHdrID {
            get {
                return this.mobInvHdrIDField;
            }
            set {
                this.mobInvHdrIDField = value;
            }
        }
        
        /// <remarks/>
        public long InvSyncID {
            get {
                return this.invSyncIDField;
            }
            set {
                this.invSyncIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TItemLot {
        
        private long lotidField;
        
        private short compidField;
        
        private long itemidField;
        
        private string lotcodeField;
        
        private string lotdescField;
        
        private string lotcreatedateField;
        
        private string lotexpiredateField;
        
        private long prodorderidField;
        
        private decimal prodorderlotqtyField;
        
        private long erplotidField;
        
        private string dbreccreatedateField;
        
        private int dbreccreateuserField;
        
        private string dbrecmoddateField;
        
        private int dbrecmoduserField;
        
        private string dbreccreatehostField;
        
        private string dbrecmodhostField;
        
        /// <remarks/>
        public long lotid {
            get {
                return this.lotidField;
            }
            set {
                this.lotidField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public long itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        public string lotcode {
            get {
                return this.lotcodeField;
            }
            set {
                this.lotcodeField = value;
            }
        }
        
        /// <remarks/>
        public string lotdesc {
            get {
                return this.lotdescField;
            }
            set {
                this.lotdescField = value;
            }
        }
        
        /// <remarks/>
        public string lotcreatedate {
            get {
                return this.lotcreatedateField;
            }
            set {
                this.lotcreatedateField = value;
            }
        }
        
        /// <remarks/>
        public string lotexpiredate {
            get {
                return this.lotexpiredateField;
            }
            set {
                this.lotexpiredateField = value;
            }
        }
        
        /// <remarks/>
        public long prodorderid {
            get {
                return this.prodorderidField;
            }
            set {
                this.prodorderidField = value;
            }
        }
        
        /// <remarks/>
        public decimal prodorderlotqty {
            get {
                return this.prodorderlotqtyField;
            }
            set {
                this.prodorderlotqtyField = value;
            }
        }
        
        /// <remarks/>
        public long erplotid {
            get {
                return this.erplotidField;
            }
            set {
                this.erplotidField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatedate {
            get {
                return this.dbreccreatedateField;
            }
            set {
                this.dbreccreatedateField = value;
            }
        }
        
        /// <remarks/>
        public int dbreccreateuser {
            get {
                return this.dbreccreateuserField;
            }
            set {
                this.dbreccreateuserField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmoddate {
            get {
                return this.dbrecmoddateField;
            }
            set {
                this.dbrecmoddateField = value;
            }
        }
        
        /// <remarks/>
        public int dbrecmoduser {
            get {
                return this.dbrecmoduserField;
            }
            set {
                this.dbrecmoduserField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatehost {
            get {
                return this.dbreccreatehostField;
            }
            set {
                this.dbreccreatehostField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmodhost {
            get {
                return this.dbrecmodhostField;
            }
            set {
                this.dbrecmodhostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WMSSyncService.intranet.albio.gr/")]
    public partial class TransCodeHeader {
        
        private long ftrIDField;
        
        private short compidField;
        
        private short branchidField;
        
        private string tradecodeField;
        
        private int fromstoreidField;
        
        private int tostoreidField;
        
        private string branchnameField;
        
        private string transdateField;
        
        /// <remarks/>
        public long FtrID {
            get {
                return this.ftrIDField;
            }
            set {
                this.ftrIDField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public string tradecode {
            get {
                return this.tradecodeField;
            }
            set {
                this.tradecodeField = value;
            }
        }
        
        /// <remarks/>
        public int fromstoreid {
            get {
                return this.fromstoreidField;
            }
            set {
                this.fromstoreidField = value;
            }
        }
        
        /// <remarks/>
        public int tostoreid {
            get {
                return this.tostoreidField;
            }
            set {
                this.tostoreidField = value;
            }
        }
        
        /// <remarks/>
        public string branchname {
            get {
                return this.branchnameField;
            }
            set {
                this.branchnameField = value;
            }
        }
        
        /// <remarks/>
        public string transdate {
            get {
                return this.transdateField;
            }
            set {
                this.transdateField = value;
            }
        }
    }
}
